config/routes.rb
Rails.application.routes.draw do
  resources :practices
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/practice.rb
class Practice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :set_practice, only: %i[ show edit update destroy ]

  # GET /practices or /practices.json
  def index
    @practices = Practice.all
  end

  # GET /practices/1 or /practices/1.json
  def show
  end

  # GET /practices/new
  def new
    @practice = Practice.new
  end

  # GET /practices/1/edit
  def edit
  end

  # POST /practices or /practices.json
  def create
    @practice = Practice.new(practice_params)

    respond_to do |format|
      if @practice.save
        format.html { redirect_to practice_url(@practice), notice: "Practice was successfully created." }
        format.json { render :show, status: :created, location: @practice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practices/1 or /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.html { redirect_to practice_url(@practice), notice: "Practice was successfully updated." }
        format.json { render :show, status: :ok, location: @practice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1 or /practices/1.json
  def destroy
    @practice.destroy

    respond_to do |format|
      format.html { redirect_to practices_url, notice: "Practice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def practice_params
      params.require(:practice).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/practices/_form.html.erb
<%= form_with(model: practice) do |form| %>
  <% if practice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
        <% practice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/practices/_practice.html.erb
<div id="<%= dom_id practice %>">
  <p>
    <strong>Name:</strong>
    <%= practice.name %>
  </p>

</div>

app/views/practices/edit.html.erb
<h1>Editing practice</h1>

<%= render "form", practice: @practice %>

<br>

<div>
  <%= link_to "Show this practice", @practice %> |
  <%= link_to "Back to practices", practices_path %>
</div>

app/views/practices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Practices</h1>

<div id="practices">
  <% @practices.each do |practice| %>
    <%= render practice %>
    <p>
      <%= link_to "Show this practice", practice %>
    </p>
  <% end %>
</div>

<%= link_to "New practice", new_practice_path %>

app/views/practices/new.html.erb
<h1>New practice</h1>

<%= render "form", practice: @practice %>

<br>

<div>
  <%= link_to "Back to practices", practices_path %>
</div>

app/views/practices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @practice %>

<div>
  <%= link_to "Edit this practice", edit_practice_path(@practice) %> |
  <%= link_to "Back to practices", practices_path %>

  <%= button_to "Destroy this practice", @practice, method: :delete %>
</div>